GET http://localhost:5037/users

###
POST http://localhost:5037/users
Content-Type: application/json

{
    "name": "Without By Pass Value",
    "email": "withoutpypass@example.com",
    "password": "pawa@12345",
    "ByPassUserName": false
}